################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Utilities/STM32469I-Discovery/stm32469i_discovery.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_audio.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_eeprom.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_lcd.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_qspi.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_sd.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_sdram.c \
../Utilities/STM32469I-Discovery/stm32469i_discovery_ts.c 

OBJS += \
./Utilities/STM32469I-Discovery/stm32469i_discovery.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_audio.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_eeprom.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_lcd.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_qspi.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_sd.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_sdram.o \
./Utilities/STM32469I-Discovery/stm32469i_discovery_ts.o 

C_DEPS += \
./Utilities/STM32469I-Discovery/stm32469i_discovery.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_audio.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_eeprom.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_lcd.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_qspi.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_sd.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_sdram.d \
./Utilities/STM32469I-Discovery/stm32469i_discovery_ts.d 


# Each subdirectory must supply rules for building sources it contributes
Utilities/STM32469I-Discovery/stm32469i_discovery.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_audio.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_audio.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_audio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_eeprom.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_eeprom.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_eeprom.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_lcd.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_lcd.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_lcd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_qspi.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_qspi.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_qspi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_sd.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_sd.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_sd.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_sdram.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_sdram.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_sdram.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Utilities/STM32469I-Discovery/stm32469i_discovery_ts.o: ../Utilities/STM32469I-Discovery/stm32469i_discovery_ts.c Utilities/STM32469I-Discovery/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32 -DSTM32F4 -DSTM32F469NIHx -DSTM32F469I_DISCO -DDEBUG -DSTM32F469xx -DUSE_HAL_DRIVER -c -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9325" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s25fl512s" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/cs43l22" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ili9341" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire480272" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q512a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/s5k5cag" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/mfxstm32l152" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/device" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q128a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ts3510" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7735" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc/Legacy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis302dl" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/otm8009a" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/STM32469I-Discovery" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe1600" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/Common" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ov2640" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/l3gd20" -I"E:/STM32/workspace/projects/dsihost-test-5/HAL_Driver/Inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/stmpe811" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lis3dsh" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/wm8994" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Fonts" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/n25q256a" -I"E:/STM32/workspace/projects/dsihost-test-5/inc" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ls016b8uy" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ft6x06" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/exc7200" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/st7789h2" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Log" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/ampire640480" -I"E:/STM32/workspace/projects/dsihost-test-5/Utilities/Components/lsm303dlhc" -I"E:/STM32/workspace/projects/dsihost-test-5/CMSIS/core" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Utilities/STM32469I-Discovery/stm32469i_discovery_ts.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

